include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
analyzer:
  errors:
    invalid_annotation_target: false
  exclude: [lib/**.g.dart, lib/**.config.dart, lib/**.freezed.dart]
